### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by johnwils** [copleykj/react-native-meteor#1]
Thank you for the efforts to maintain this repo. I found a small typo in the readme.

https://github.com/copleykj/react-native-meteor/blame/master/README.md#L116

`import Meteor, { withTracker } from 'react-native-meteor';`

should be

`import Meteor, { useTracker } from 'react-native-meteor';`

**Comment by copleykj** [comment]
Thanks for the fix! :slightly_smiling_face:
