### ISSUE TITLE
Can't resolve 'react-native' | for web app project

### ISSUE THREAD

**Issue by barrymichaeldoyle** [copleykj/react-native-meteor#3]
I'm experience the following issue when I `import Meteor from '@socialize/react-native-meteor'`

> Module not found: Can't resolve 'react-native' in '...\node_modules\@react-native-community\netinfo\lib\module\internal'

This is for use with a web app. So I shouldn't need to install the RN plugins if I recall the docs correctly.

**Comment by copleykj** [comment]
You are correct! It's very odd that this code path could execute. Could you outline your build setup, or if possible, provide a very minimal reproduction where the build fails with this error.

**Comment by copleykj** [comment]
@barrymichaeldoyle can you elaborate on which bundler you are using for your project?

**Comment by gamedolphin** [comment]
This happens when using this library with `create-react-app` as well.

**Comment by copleykj** [comment]
Ok, so it turns out that while node, meteor, and metro all support conditionally requiring modules, not all bundlers (webpack in particular) do. I think we can work around this with a bit of dependency injection and I'll see about getting a new release out very soon.

**Comment by copleykj** [comment]
All fixed in the freshly published v3.0.0
