### ISSUE TITLE
Disconnected from DDP server

### ISSUE THREAD

**Issue by Evert-jvv** [copleykj/react-native-meteor#6]
When I try to connect to a local meteor project (using the todos example from the meteor site) I get the following error:

Disconnected from DDP server.

I am connecting to the todo app using: Meteor.connect('ws://localhost:3000/websocket');
I also tried my IP instead: Meteor.connect('ws://192.168.x.xx:3000/websocket');

running react native app with Expo

on MacOS

**Comment by copleykj** [comment]
The connection address needs to be the IP of a computer where the Meteor server is running. `localhost` will not work because the app is running on a mobile device and so it will try to connect to that device at port 3000.

**Comment by Evert-jvv** [comment]
I have no idea if this is related, but had an issue with expo today due to an issue with watchman, re-installed it with brew and now I am getting "Connected to DDP server."

**Comment by copleykj** [comment]
Glad you got it sorted out.
